export const paintings = [
  {
    id: 1,
    title: "White & Blue",
    artist: "Tatiana Bugaenko",
    price: 27200,
    description: "White sands on the coast of the sea and Blue water and sky",
    medium: "Oil on Canvas",
    img: require("../images/whiteandblue.jpg").default,
  },
  {
    id: 2,
    title: "Fragments",
    artist: "Milan Terzic",
    price: 15100,
    description: "Through the work, which includes the poetics of lyrical abstraction, the simplicity of the light, the expression of the pure form of full-bodied content, with which the artist wants everything to express in his art works.",
    medium: "New Media on Canvas",
    img: require("../images/fragments.jpg").default,
  },
  {
    id: 3,
    title: "Summer trip",
    artist: "Tatiana Bugaenko",
    price: 970,
    description: "Summer trip in California, beautifull nature, blue sky and water.",
    medium: "Oil on Canvas",
    img: require("../images/summertrip.jpg").default,
  },
  {
    id: 4,
    title: "Roses Painting",
    artist: "Tatiana Bugaenko",
    price: 790,
    description: "Roses in the interior, pink bouquet on the window.",
    medium: "Oil on Canvas",
    img: require("../images/rosespainting.jpg").default,
  },
  {
    id: 5,
    title: "Lover of Sunsets",
    artist: "Emy-Rose OZ",
    price: 7680,
    description: "This painting is from my “Visual Poems” Collection, it’s finished with semi-gloss coat of protective varnish.",
    medium: "Oil on Canvas",
    img: require("../images/loverofsunsets.jpg").default,
  },
  {
    id: 6,
    title: "Summer joy",
    artist: "Marta Zawadka",
    price: 1750,
    description: "This series features very personal paintings. It's a return to my childhood, when I painted everywhere I could: walls, floors, furnitures... it was impossible to stop me. That's how I built myself and my world. This is a story about perseverance and persistence.",
    medium: "Acrylic",
    img: require("../images/summerjoy.jpg").default,
  },
  {
    id: 7,
    title: "Pleasure",
    artist: "Marta Zawadka",
    price: 26350,
    description: "This series features very personal paintings. It's a return to my childhood, when I painted everywhere I could: walls, floors, furnitures... it was impossible to stop me. That's how I built myself and my world. This is a story about perseverance and persistence.",
    medium: "Acrylic",
    img: require("../images/pleasure.jpg").default,
  },
  {
    id: 8,
    title: "Rebound",
    artist: "Chuck Hipsher",
    price: 5350,
    description: "At some time or another, all of us are laid-out by some sort of setback... Financial, emotional, physical, spiritual. You name it, it will find you one day and you will be faced with a decision: 'What now?'. As one old friend put it, 'It's not what happens to you, it's how you react to what happens to you.' I believe in our innate ability to start over. It's not always fun, but that's life. I hope this piece inspires anyone who sees it and is down on their luck to not give up. After all, we are all constantly starting over. Hang in there. You will rebound.",
    medium: "Acrylic on Canvas",
    img: require("../images/rebound.jpg").default,
  },
  {
    id: 9,
    title: "1 more year",
    artist: "Chuck Hipsher",
    price: 5150,
    description: "Based on the current Coronavirus situation, I hope for all of us that we can indeed be here 1 year from now. And if not, may our souls be blessed and free of these earthly bounds.",
    medium: "Acrylic on Canvas",
    img: require("../images/onemoreyear.jpg").default,
  },
  {
    id: 10,
    title: "New York City rhythm",
    artist: "Marta Zawadzka",
    price: 2450,
    description: "This series features paintings inspired by my travels, people I've met, their stories, sounds and colors, everything what creates the city and it's spirit. Vibrant colors, texture, lines allowes me to express the dynamics of life and to catch the ephemeral spirit of the city.",
    medium: "Spary Paint on Canvas",
    img: require("../images/nycrhythm.jpg").default,
  },
  {
    id: 11,
    title: "Hommage à Pythagore",
    artist: "Slavomir Zombek",
    price: 120,
    description: "Gou Gu Xian theorem - Baudhayana theorem - Pythagoras' theorem - a² + b² = c²",
    medium: "Paper on Paper",
    img: require("../images/pythagore.jpg").default,
  },
  {
    id: 12,
    title: "The Blue Zone",
    artist: "Arun Prem",
    price: 145,
    description: "Ready to hang. textured oil on canvas made with brush and palette knife. The lily pads seem to be airborne in the illusion created by the light and dark shadows in water",
    medium: "Oil on Canvas",
    img: require("../images/bluezone.jpg").default,
  },
  {
    id: 13,
    title: "Night Swim",
    artist: "Chuck Hipsher",
    price: 4350,
    description: "Inspired by skinny-dipping in the summer of 1995 off the beach in Bridgehampton, Long Island. Also on Nantucket. Also elsewhere.",
    medium: "Acrylic on Canvas",
    img: require("../images/nightswim.jpg").default,
  },
  {
    id: 14,
    title: "Snake Charmer",
    artist: "Chuck Hipsher",
    price: 7400,
    description: "Inspired by my old painter (former) friend, Wesley Kimler. He's a genius, and he knows it.",
    medium: "Acrylic on Canvas",
    img: require("../images/snakecharmer.jpg").default,
  },
  {
    id: 15,
    title: "Untitled 0006",
    artist: "Pava Wülfert",
    price: 470,
    description: "In my work use the painting as an experimental laboratory in which he can explore all his painterly operations. Analytical paintings that emphasize the combination of visual expression fragment, diversity, heterogeneity, multiculturalism, interculturality, hybridization, mixture, recycling, migration, stains, error,dots and lines are necessary tools to create a new concept of landscape and figure. to engage the viewer in a visual conversation.",
    medium: "Acrylic on Canvas",
    img: require("../images/untitled.jpg").default,
  },
  {
    id: 16,
    title: "Untitled 1906",
    artist: "Pava Wülfert",
    price: 8410,
    description: "Painting has to do with many things: The colors, surfaces, shapes, lines, dots, strokes, gestures, stains and sensations. I emphasize the combination of visual expressions of error, diversity, heterogeneity, multiculturalism, hybridization, mixing, recycling, migration, interculturality, conflict and fragment. These are necessary tools to create a new concept of landscape and form.",
    medium: "Acrylic on Canvas",
    img: require("../images/untitled1906.jpg").default,
  },
  {
    id: 17,
    title: "Gemstone Series",
    artist: "Gorkem Dikel",
    price: 157,
    description: "Ruby IV",
    medium: "Acrylic on Canvas",
    img: require("../images/ruby.jpg").default,
  },
  {
    id: 18,
    title: "The Rip",
    artist: "Gorkem Dikel",
    price: 3475,
    description: "Whilst forming her artistic practices around the transformation and motion of the matter in space and its interaction made with hypothetical void, she brings some extraordinary dimensions and oscillations through juxtapositions and superpositons. What is solid evaporates, liquid freezes, air solidifies, what is behind appears in the front and the atoms the reality is made of are torn apart.",
    medium: "Acrylic on Canvas",
    img: require("../images/rip.jpg").default,
  },
  {
    id: 19,
    title: "Mirage at Sea",
    artist: "Changsoon Oh",
    price: 11750,
    description: "Artist, ocean lover, endeavor to capture the ethereal element of light in the material medium of pigment, I am seizing mirage phenomenon, 'distant shoreline may appear to paradise island, isle, many objects etc..'",
    medium: "Acrylic on Canvas",
    img: require("../images/mirageatsea.jpg").default,
  },
  {
    id: 20,
    title: "Beach at Night",
    artist: "Changsoon Oh",
    price: 3510,
    description: "On the Beach at Night Alone by Walt Whitman",
    medium: "Oil on Canvas",
    img: require("../images/beachatnight.jpg").default,
  },
  {
    id: 21,
    title: "Evening Glow",
    artist: "Céline van Hanja",
    price: 4270,
    description: "Just like the Bauhaus Painter Lyonel Feininger, light-transmitting color areas are shown in this painting to represent atmospherically charged moods. The mastery of multiple modernist motives has shifted to meteorological phenomena of the sea. The painterly idea remains the same.",
    medium: "Oil on Canvas",
    img: require("../images/enevingglow.jpg").default,
  },
  {
    id: 22,
    title: "Luminous Bay",
    artist: "Céline van Hanja",
    price: 2310,
    description: "The reflections of the sun make the bay of Saint Tropez shine. Yellow to yellow, just like Van Gogh's sunflowers. The background perspective and the scenic image refer to Japanese printmaking. The straight lines in the foreground form terraces with a view of the Mediterranean. Everything in a luminous yellow glow.",
    medium: "Oil on Canvas",
    img: require("../images/luminousbay.jpg").default,
  },
  {
    id: 23,
    title: "Flowers for Hawthorne",
    artist: "Sarah Giannobile",
    price: 1346,
    description: "The linear forms are inspired by invented narratives that develop through the intuitive process. These lyrical abstract compositions are spontaneous by nature and inspired by my dreams and memories of my past experiences. This painting is made with gouache, and acrylic on 9' x 12' stretched canvas that has been prepared with traditional gesso ground of marble plaster. The edges have 1 3/4' profile, are gallery wrapped (no staples) and finished so no frame is required.",
    medium: "Oil on Canvas",
    img: require("../images/flowers.jpg").default,
  },
  {
    id: 24,
    title: "Landscape for Hawthorne",
    artist: "Sarah Giannobile",
    price: 1346,
    description: "The linear forms are inspired by invented narratives that develop through the intuitive process. These lyrical abstract compositions are spontaneous by nature and inspired by my dreams and memories of my past experiences. This painting is made with gouache, and acrylic on 9' x 12' stretched canvas that has been prepared with traditional gesso ground of marble plaster. The edges have 1 3/4' profile, are gallery wrapped (no staples) and finished so no frame is required.",
    medium: "Gouache",
    img: require("../images/landscape.jpg").default,
  },


]